app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|


Route::get('/', function () {
    return view('welcome');
});

Route::auth();
Route::get('/auth/confirm/{id}/{token}', 'Auth\AuthController@getConfirm');


Route::get('/home', 'HomeController@index');
*/

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/home', 'PagesController@home');

Auth::routes();

Route::post('/attachments', 'AttachmentController@store')->name('attachments.store');

Route::get('/tag/{slug}', 'TagController@tag')->name('posts.tag');

Route::get('/confirm/{id}/{token}', 'Auth\RegisterController@confirm');
Route::get('/profil', ['uses' => 'UsersController@edit', 'as' => 'profilEdit']);
Route::post('/profil', ['uses' => 'UsersController@update', 'as' => 'profilUpdate']);

Route::get('/user/{id}', 'UsersController@allById');

Route::post('/comments', 'CommentsController@store');
Route::get('/comments', 'CommentsController@index');
Route::delete('comments/{comment}', 'CommentsController@destroy');

Route::resource('/posts', 'PostsController');
Route::get('/posts/{slug}', ['uses' => 'PostsController@categories'])->where('slug', '[a-z\-]+');
Route::resource('/categories', 'CategoriesController');
Route::resource('/projects', 'ProjectsController');

Route::get('post/like/{id}', ['as' => 'post.like', 'uses' => 'LikeController@likePost']);

Route::get('/', 'HomeController@index');

app/Projects.php
<?php

namespace App;

use Intervention\Image\ImageManagerStatic;
use Illuminate\Support\Facades\Event;

class Projects extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id',
    ];

    public $dates = [
        'created_at', 'updated_at',
    ];

    public static function boot()
    {
        parent::boot();
        static::deleted(function($instance){
            if($instance->highlight){
                unlink(public_path() . $instance->highlight);
            }
            $instance->posts()->update(['projects_count' => DB::raw('projects_count - 1')]);
            foreach($instance->posts()->where('projects_count', 0)->get() as $post){
                Event::fire('eloquent.deleted: ' . get_class($post), $post);
            }
            $instance->posts()->where('projects_count', 0)->delete();
            return true;
        });
    }

    public function posts(){
        return $this->belongsToMany('App\Posts');
    }

    public function categories()
    {
        return $this->belongsTo('App\Categories');
    }

    public function getHighlightAttribute($highlight)
    {
        if($highlight){
            return "/img/highlight/" .ceil($this->id / 1000) . "/{$this->id}.jpg";
        }
        return false;
    }

    public function setHighlightAttribute($highlight)
    {
        if( is_object($highlight) && $highlight->isValid() ){
            self::saved(function($instance) use ($highlight){
                $dir = public_path() . "/img/highlight/" . ceil($instance->id / 1000);
                if(!file_exists($dir)){
                    mkdir($dir, 0777, true);
                }
                ImageManagerStatic::make($highlight)->fit(300,300)->save("$dir/{$instance->id}.jpg");
            });
            $this->attributes['highlight'] = true;
        }
    }

    public function getAgeAttribute()
    {
        return $this->created_at->diffForHumans();
    }
}

resources/views/pages/home.blade.php
@extends('layouts.sidebar')

@section('main')
    <h2>Derniers projets</h2>
    @foreach($tags as $tag)
        <a style="font-size:{{ 1 + round($tag->post_count / $max, 2) }}rem; color:grey" href="{{ route('posts.tag', ['slug' => $tag->slug]) }}">#{{ $tag->name }}</a>
    @endforeach
    <main class="arts">
    <!--div class="row"-->
        @foreach($posts as $post)
            <article class="arts-article">
                <div class="arts-article-thumb">
                    <img class="arts-article-thumb-picture" src="{{ url($post->image('thumb')) }}" alt="">
                </div>
                <div class="arts-article-preview">
                    <div class="arts-article-preview-window">
                        <img class="arts-article-preview-window-avatar" src="img/avatars/{{ $post->user()->value('id') }}.jpg" alt="Auteur de l'article" height="100">
                        <p class="arts-article-preview-window-author">{{ $post->user()->value('firstname') }}<br>{{ $post->user()->value('lastname') }}</p>
                    </div>
                    <h4 class="arts-article-preview-title"><a href="{{ action('PostsController@show', $post) }}">{{ $post->name }}</a></h4>
                    <p class="arts-article-preview-txt">{{ substr(strip_tags($post->content), 0, 140) }}</p>
                    <div class="arts-article-preview-info">
                        <p class="arts-article-preview-info-spec">
                            <a href="{{ action('PostsController@show', $post) }}">Voir le projet</a>
                            <!--span class="glyphicon glyphicon-eye-open"></span><span class="number">2367</span>
                            <span class="glyphicon glyphicon-thumbs-up"></span><span class="number">1892</span-->
                        </p>
                        <p class="arts-article-preview-info-date">{{ substr($post->created_at, 0, 10) }}</p>
                    </div>
                </div>
            </article>
        @endforeach

    <!--p class="text-right">
        <a class="btn btn-primary" href="{{-- action('PostsController@index') --}}">Voir toutes les photos</a>
    </p-->
    </main>
@endsection



{{--@section('sidebar')--}}
    <!--h2>Filtrer </h2>
    <div class="list-group">
        {{--@foreach($categories as $s)--}}
            <a class="list-group-item" href="{{-- action('PostsController@categories', $s->slug) --}}">
                {{-- $s->name --}}
            </a>
        {{--@endforeach--}}
    </div>

    <h2>Nouveaux projets </h2>
    <div class="list-group">
        {{--@foreach($projects as $project)--}}
            <div class="list-group-item">
                <h4 class="list-group-item-heading">{{-- $project->name --}}</h4>
                <p class="list-group-item-text">{{-- $project->age --}} ans</p>
                <a href="{{-- action('ProjectsController@show', $project) --}}">Voir le projet</a>
            </div>
        {{--@endforeach--}}
    </div>-->
{{--@endsection--}}